project:
  type: website
  output-dir: "docs"
lang: fr
website:
  title: "LaTeXR"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - sommaire.qmd
      - docphilmstat.qmd
      - chronologie.qmd
      - presentation.qmd
      - tarifs.qmd
      - materiel.qmd
      - about.qmd
  page-footer:
    left: "Copyright 2024, philippe MICHEL"
    right:
      - icon: github
        href: https://github.com/philippemichel
      - icon: twitter
        href: https://twitter.com/PhiippeMICHEL
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "DocPhilmStat"
        contents:
          - docphilmstat.qmd
          - chronologie.qmd
          - presentation.qmd
          - tarifs.qmd
          - materiel.qmd
          - about.qmd
      - section: "Blog"
        contents:
          - blog/index.qmd
format:
  html:
    page-layout: full
    theme:
     light:
       - sandstone
       - custom.scss
     dark: cyborg
    css: styles.css

    fontsize: 1.1em
    toc: true
    links:
    - icon: twitter
      text: twitter
      href: https://twitter.com/PhiippeMICHEL
    - icon: github
      text: Github
      # href: https://github.com/philippemichel



