project:
  type: website
  output-dir: docs
website:
  title: "latexr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - docphilmstat.qmd
      - présentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_depth: 3