project:
  type: website
  output-dir: "docs"
lang: fr
website:
  title: "LaTeXR"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - docphilmstat.qmd
      - chronologie.qmd
      - presentation.qmd
      - tarifs.qmd
      - materiel.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "DocPhilmStat"
        contents:
          - docphilmstat.qmd
          - chronologie.qmd
          - presentation.qmd
          - tarifs.qmd
          - materiel.qmd
          - about.qmd
      - section: "Blog"
        contents:
          - blog.qmd
format:
  html:
    page-layout: full
    theme:
     light: sandstone
     dark: cyborg
    css: styles.css
    toc: true
    links:
    - icon: twitter
      text: twitter
      href: https://twitter.com/PhiippeMICHEL
    - icon: github
      text: Github
      # href: https://github.com/philippemichel



