project:
  type: website
  output-dir: "docs"
website:
  title: "LaTeXR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - docphilmstat.qmd
      - chronologie.qmd
      - tarifs.qmd
format:
  html:
    theme:
     light: flatly
     dark: darkly
    css: styles.css
    toc: true
    links:
    - icon: twitter
      text: twitter
      href: https://twitter.com/PhiippeMICHEL
    - icon: github
      text: Github
      # href: https://github.com/philippemichel
