project:
  type: website
  output-dir: "docs"
lang: fr
website:
  image: violons.png
  title: "DocPhilmStat"
  search:
    location: sidebar
    type: textbox
  navbar:
    logo: violons.png
    background: info
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - chronologie.qmd
      - tarifs.qmd
      - presentation.qmd
      - materiel.qmd
      - about.qmd
  page-footer:
    left: "Copyright 2024, philippe MICHEL"
    right:
      - icon: github
        href: https://github.com/philippemichel
      - icon: twitter
        href: https://twitter.com/PhiippeMICHEL
      - icon: mailbox
        text: mail
        href: mailto:docphilmstat@gmail.com
  sidebar:
    style: "docked"
    pinned: true
    search: true
    contents:
      - index.qmd
      - section: "DocPhilmStat"
        contents:
          - chronologie.qmd
          - presentation.qmd
          - tarifs.qmd
          - materiel.qmd
          - about.qmd
      - section: "Blog"
        contents:
          - blog/index.qmd
  open-graph:
    locale: fr_FR
    site-name: DocPhilmStat
format:
  html:
    page-layout: full
    highlight-style: ayu
    theme:
      light:
        - sandstone
        - custom.scss
      dark: cyborg
    fontsize: 1.2em
    toc: true
