---
title: "Déroulé de votre étude"
subtitle: "Au travail !"
---


Pour une étude clinique correcte il faut prévoir environ 5 ans. Rassurez-vous pour une thèse, sur un travail simple, on peut aller beaucoup plus vite mais il faut tout de même prévoir au minimum 1 an. Voyons en détail les différentes étapes qui correspondent plus ou moins aux sections de tout article ou thèse. 


::: {.callout-note}
## Exemple

Nous allons prendre comme exemple un travail su le BPCO aux urgences. 

La question posée est *"Est-ce que la SpO~2~ est un bon marqueur de la sévérité de la BPCO aux urgences ?"* (spoiler : c'est un très mauvais critère).
:::

::: {.panel-tabset}

# Introduction

Vous avez une idée de départ il vous faut l'affiner. Dans notre exemple, sévérité OK mais quel critère ? . On peut par exemple prendre le nombre de recours à la ventilation invasive ou non. On prend en compte une VNI brève aux urgences ? Après transfert en réa, dans quel délai ? etc. Il vous faut arriver à une formulation claire de votre question :
*Est-ce que la SpO~2~ est un bon marqueur du recours rapide (moins de 48 h) à la ventilation invasive chez les BPCO GOLD II ou plus ?*

Même en admettant que vous connaissiez bien votre sujet, il vous faut faire une revue de la littérature. Ça affinera votre vision du problème, vous donnera des idées, des méthodes pour aborder le problème. Cette étape revient à rédiger la partie *Introduction* de votre travail.

::: {.callout-tip}
## Mon apport

Il s'agit là de vous approprier le sujet. C'est un travail personnel, je ne peux rien faire pour vous. 
:::

# Matériel et Méthodes

C'est la partie la plus importante de votre travail. Vous allez décrire votre population, vos critères d'inclusion et d'exclusion, vos méthodes statistiques, vos tests, vos hypothèses, vos variables, etc. Mais aussi la plus rébarbative à lire & la plus complexe à écrire.

La première étape est de définir exactement le design de votre travail : rétrospectif ? Interventionnel ? 
Souvenez-vous de vos cours de LCA !

Ensuite, il vous faut définir votre population. Dans notre exemple, on va prendre tous les patients qui ont été admis aux urgences pour une BPCO. Mais qu'est-ce qu'une BPCO ? Il faut définir les critères d'inclusion et d'exclusion.

Il faut maintenant définir les variables que vous allez devoir collecter. Ni trop, ni trop peu. Il vous faudra bien entendu la SpO~2~ à l'admission mais aussi d'autres variables permettant de chercher si certains groupes de malades bénéficieraient plus de cette approche (âge, gravité, certains antécédents...). Sans oublier que plus il y a de variables plus il y aura de travail à fournir. Idéalement il faudrait faire une liste des variables (*codebook*) avec leur nom, l'unité, le type de variable (numérique, catégorielle, etc.) etc. 


```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
#| label: codebook
#| tbl-name: Codebook

library(tidyverse)
library(kableExtra)

tibble(
  variable = c("date_adm", "age", "sexe", "spo2"),
  description = c("Date d'admission", "Âge", "Sexe", "SpO2 à l'admission"),
  unite = c("DD/MM/YY", "années", "", "%"),
  limite = c("01/01/2022 - 31/12/2024", "18 - 110", "F ou M", "50 - 100")
) |> 
  kable(format = "html", align = "l") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE)
```


Le seul calcul qui doit être fait à ce stade est le nombre de cas nécessaires. On se base sur la bibliographie & des méthodes statistiques. 

::: {.callout-tip}
## Mon apport

C'est à vous de définir votre type d'étude selon les possibilités locales etc.

Ensuite je peux vous aider à rédiger le protocole, à définir les variables, à les coder etc. 

Bien entendu je peux calculer le nombre des cas & rédiger la plan d'analyse statistique. 
:::

Tout cela vous donnera une bonne base pour rédiger votre partie *Matériel et Méthodes*.

## Base de données

Toutes ces données il va falloir les stocker. Deux solutions simples existent : 

- Un formulaire en ligne type [Google Forms](https://www.google.fr/intl/fr/forms/about/) ou = [LymeSurvey](https://www.limesurvey.org/fr) par ex.). C'est simple, rapide, gratuit mais attention à la sécurité.
- Un tableur (type Excel). Ça peut paraître simple mais c'est plein de pièges & la saisie peut être longue & source d'erreurs. Quelques trucs & techniques permettent de pallier à beaucoup de ces erreurs.

::: {.callout-tip}
## Mon apport

Pour un formulaire en ligne je peux me charger de le configurer. 

Pour un tableur je peux soit le créer complètement soit simplement vérifier ou améliorer votre travail. 
:::

::: {.callout-warning}
## Attention !

Il ne faut pas oublier la partie administrative : déclaration à la CNIL & demande d'autorisation au CPP. Là je ne peux rien pour vous si ce n'est vous aider à rédiger la demande pour le CPP qui ce résume (presque) à l'Introduction & les Matériel et Méthodes. Votre service (surtout en CHU) doit avoir un modèle pré-établit dans ses tiroirs.

Et ne perdez pas de temps : il est hors de question d'inclure le moindre patient dans l’étude avant d'avoir l'accord du CPP.
:::

## recueil des données

Là, c'est à vous de bosser. 

# Résultats

L'analyse des données commence toujours par un nettoyage & une mise en forme même si le recueil a été très bien fait. Il faut vérifier les valeurs aberrantes, les doublons, les valeurs manquantes, mettre en forme les données catégorielles... Bien entendu si je doit récupérer un classeur Excel mal organisé je vais y passer beaucoup, beaucoup plus de temps  &  je vais vous facturer beaucoup, beaucoup plus. Un graphique ou un tableau récapitulatif de l'étude avec le nombre de variables par catégorie, le nombre de valeurs manquantes & un résumé rapide des résultats seront rendus au plus vite.

Ensuite on commence par un ou plusieurs tableaux descriptifs & des graphiques pour les valeurs essentielles. Puis, enfin, la réponse à la question principale (le `p< 0,05`). Outre ce chiffre, on recherchera souvent des corrélations avec d'autres évènements, des facteurs  favorisants (*Est-ce que la SpO~2~ est un meilleur facteur prédictif chez les patients Gold4 ?*)*. Pour une analyseassez simple on rendra un tableau récapitulatif des résultats avec les p-values item par item puis une analyse multivariée par régression (logistique, linéaire, etc.). Dans d'autres cas un score de propension pourra être calculé ou autre, le design de l'analyse dépend du travail. Bien entendu des graphiques seront réalisés pour illustrer les résultats.

::: {.callout-tip}
## Mon apport

Là, pas de détail, je fais tout. Et le rapport rendu correspond pratiquent à la partie *Résultats* de votre travail.
:::

# Discussion

À  vous de travailler. Je peux éventuellement relire mais l'avis de votre directeur de thèse ou d'un collègue sera plus utile.

# Divers

**Points de détail**

- Je travaille vite : pour une analyse statistique simple je peux rendre un rapport dans la semaine. De votre coté vous vous devez d'être réactif si je vous demande des précisions. 

- Comme vous pouvez le deviner en lisant ce site si je maîtrise à peu près correctement la technique le coté esthétique m'échappe complètement. Les graphiques que je vais vous rendre seront, je l’espère, clairs & informatifs mais ni très originaux ni fignolés dans l'esthétique. 
Maintenant, si vous le souhaitez, je peux modifier certaines choses par ex. mettre une image en fond (très moche à mon avis) ou remplacer les rectangles des histogrammes par des figures etc. À vous de voir.

- De base j'utilise des échelles de couleurs compatibles avec les troubles de la vision des couleurs.
:::


