---
title: "Matériel & Logiciels"
---
 Petite présentation de mon matériel & des logiciels que j'utilise. 
 
 Page a priori sans aucun intérêt mais si vous êtes curieux...
 
# Matériel
 
 De nos jours n'importe quel ordinateur récent fera l'affaire pour des études cliniques (au max quelques milliers de cas pour une centaine de variables). Si vous travaillez sur du génome (quelques millions de cas) le problème est différent. 
 
 $\mathbb{R}$ travaille uniquement en mémoire vive. il faut donc prévoir large, 16 Go est un strict minimum.
 
 Deux écrans me parait être un minimum (je n'ai pas encore essayé les grands écrans courbes). Un pour le code, un secondaire pour les résultats, la doc, les mails...
 
 Un réseau correct, un clavier & une souris qui vous conviennent (très personnel) & voilà. Sans oublier un système de sauvegarde local.
 
 
 
# Logiciels
 
 En vieux libriste j'utilise une distribution Linux à savoir une Debian Testing avec un bureau i3.
 
 Je fais tous mes travaux statistiques avec $\mathbb{R}$ saveur tidyverse. Comme IDE j'utilise selon mon humeur [RStudio](https://posit.co/download/rstudio-desktop/) ou [Visual Studio Code](https://code.visualstudio.com/), parfois [Emacs](https://www.gnu.org/s/emacs/) avec [ESS](https://ess.r-project.org/). 
 
 Les rapports (et ce site) sont rédigés grâce à [Quarto](https://quarto.org/). 
 
 Pour les autres langages en particulier $\LaTeX$, je reste fidèle à Emacs. Pour le reste que du très classique. 


:::{.callout-tip}
## Pour me joindre

Un simple mail à <a href="mailto:docphilmstat@gmail.com">docphilmstat@gmail.com</a> ou un message sur [Twitter](https://twitter.com/PhiippeMICHEL) & je vous répondrai dans les plus brefs délais.
:::
