---
title: "Tarifs"
subtitle: "provisoires, prévisionels & non contractuels"
format: html
---

Je ne facture pas à l'heure car si je vais très vite pour certaines tâches c'est que j'ai passé beaucoup de temps à me former mais aussi à rédiger mes macros & mes scripts, temps que je ne vous facture pas directement mais que je dois prendre en compte.<br> Voir l'[histoire du coup de marteau](https://www.map-consult.com/fr/savoir-faire/le-coup-de-marteau.html).


```{r setup, echo=FALSE, message=FALSE, warning=FALSE, cache= TRUE}
#| label: tarif

library(tidyverse)
library(kableExtra)

tibble(
  Tache = c("Méthodologie", "Questionnaire en ligne", "Tableur : rédaction complète", "Tableur : correction", "Analyse statistique simple", "Analyse statistique complexe", "Travail complet"),
  Tarif = c("200 €","100 €","200 €","100 €","200 €","300 €","500 €")
) |> 
kable(format = "html", align = "l") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"), full_width = FALSE) |> 
    row_spec(7, bold = T, color = "white", background = "#D7261E") |> 
  row_spec(2:4, bold = F, color = "black", background = "#CCC6FF")
```

**10 % de réduction pour les premiers clients (jusqu'à la fin 2024)**


Comme vous le devinez je préfère travailler sur un projet du début à la fin. C'est plus intéressant pour vous & pour moi.  Mais je peux aussi vous aider sur une partie seulement.


::: {.callout-caution}
## 

"Appeler un statisticien après que l’expérience est terminée, c’est comme lui demander de faire une autopsie; il pourra seulement déterminer la cause de l’échec de l’expérience."

Ronald A. Fisher, FRS (1890-1962)
:::


# Quelques précisions 

- **Analyse simple** : Études observationnelles, sondages, analyse de pratique...

- **Analyse complexe** : Études interventionnelles sans risque pour le patient, sans médicament. Analyse rétrospective avec score de propension. *TextMining* (analyse en plein texte) ou autre technique complexe ou exotique.


## Mes limites

Si je me permets de vous proposer mes services c'est que j'ai une bonne [formation en statistiques & Une grosse expérience](presentation.html) de ce type de travail. Mais tout seul dans mon coin je ne vais pas gérer un PHRC ou une étude interventionnelle avec du médicament. 

Je n'interviens donc que sur des études [RIPH-3](moz-extension://12959df1-7aeb-4e99-a041-ebf819bc5934/content/web/viewer.html?file=https%3A%2F%2Fsfar.org%2Fwp-content%2Fuploads%2F2018%2F10%2F3-Recherche-clinique-en-anesthesie-reanimation-la-loi-Jarde-en-pratique.pdf) ou RNIPH. Je peux éventuellement faire uniquement la partie statistique d'une RIPH-2 mais pas la partie méthodologique.

# Formations

Me joindre pour en discuter.

:::{.callout-tip}
## Pour me joindre

Un simple mail à <a href="mailto:docphilmstat@gmail.com">docphilmstat@gmail.com</a> ou un message sur [Twitter](https://twitter.com/PhiippeMICHEL) & je vous répondrai dans les plus brefs délais.
:::
